version: "2.4"

services:
  calculator:
    image: campudus/calculator:latest
    container_name: calculator
    restart: always
    environment:
      - NGINX_PORT=80
    volumes:
      # sync timezone and localtime with host
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calculator.entrypoints=https"
      - "traefik.http.routers.calculator.rule=Host(`calculator.campudus.com`)"
      - "traefik.http.routers.calculator.tls=true"
      - "traefik.http.routers.calculator.tls.certresolver=default"
      - "traefik.http.routers.calculator.service=calculator"
      - "traefik.http.services.calculator.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy_grud"

networks:
  proxy:
    external: true
    name: "proxy_grud"
